#!/bin/sh
case $1 in
  remove | abort-install | disappear)
    ddl="$(dpkg-divert --list wireguard)" &&
    [ -n "$ddl" ] &&
    for p in perl5/Vyatta/Interface.pm \
             vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def \
             vyatta-cfg/templates/firewall/options/mss-clamp6/interface-type/node.def
    do
      dpkg-divert --package wireguard --rename --remove /opt/vyatta/share/"$p"
    done
esac
